# -*- coding: utf-8-unix -*-
# vim:fileencoding=utf-8:ff=unix

# ----------------------------------------------------------

PREFIX         :=
CC             := $(PREFIX)gcc
CXX            := $(PREFIX)g++
OBJC           := $(CC)
OBJCXX         := $(CXX)

CFLAGS          =       # FIXME
CXXFLAGS        =       # FIXME
OBJCFLAGS       =       # FIXME
OBJCXXFLAGS     =       # FIXME
CPPFLAGS        =       # FIXME
LDFLAGS         =       # FIXME
LDLIBS         := -lm   # FIXME

WARNADD        := -finput-charset=cp932     # FIXME

# ----------------------------------------------------------

include ../unix-common/common.mk
