# -*- coding: utf-8-unix -*-
# vim:fileencoding=utf-8:ff=unix

# ----------------------------------------------------------

PREFIX         :=
CC             := $(PREFIX)$(CC)
CXX            := $(PREFIX)$(CXX)
OBJC           := $(PREFIX)$(OBJC)
OBJCXX         := $(CXX)
AR             := $(PREFIX)$(AR)
RANLIB         := $(PREFIX)ranlib

CFLAGS          = -pthread      # FIXME
CXXFLAGS        =               # FIXME
OBJCFLAGS       =               # FIXME
OBJCXXFLAGS     =               # FIXME
CPPFLAGS        = -D_BSD_SOURCE -D_DEFAULT_SOURCE   # FIXME

WARNADD        := -finput-charset=cp932     # FIXME

# ----------------------------------------------------------

include ../unix-common/common.mk
